from django.db import models

class Conversation(models.Model):
    """
    Stores the history of the conversational assistant. 
    User authentication is handled by Django's built-in User model.
    """
    # Link to the authenticated user
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    # Message sent by the user
    user_message = models.TextField()
    
    # Response generated by the AI
    ai_response = models.TextField()
    
    # Timestamp for the conversation turn
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.timestamp.strftime('%Y-%m-%d %H:%M')}] {self.user.username}: {self.user_message[:50]}..."

    class Meta:
        ordering = ['timestamp']